{"text": "\n      \u201cBe yourself; everyone else is already taken.\u201d\n  ", "author": "\n    Oscar Wilde\n  "}
{"text": "\n      \u201cYou've gotta dance like there's nobody watching,", "author": "\n    William W. Purkey\n  "}
{"text": "\n      \u201cBe the change that you wish to see in the world.\u201d\n  ", "author": "\n    Mahatma Gandhi\n  "}
{"text": "\n      \u201cLive as if you were to die tomorrow. Learn as if you were to live forever.\u201d\n  ", "author": "\n    Mahatma Gandhi\n  "}
{"text": "\n      \u201cDarkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.\u201d\n  ", "author": "\n    Martin Luther King Jr.,\n  "}
{"text": "\n      \u201cWithout music, life would be a mistake.\u201d\n  ", "author": "\n    Friedrich Nietzsche,\n  "}
{"text": "\n      \u201cWe accept the love we think we deserve.\u201d\n  ", "author": "\n    Stephen Chbosky,\n  "}
{"text": "\n      \u201cImperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.\u201d\n  ", "author": "\n    Marilyn Monroe\n  "}
{"text": "\n      \u201cThere are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.\u201d\n  ", "author": "\n    Albert Einstein\n  "}
{"text": "\n      \u201cWe are all in the gutter, but some of us are looking at the stars.\u201d\n  ", "author": "\n    Oscar Wilde,\n  "}
{"text": "\n      \u201cFairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.\u201d\n  ", "author": "\n    Neil Gaiman,\n  "}
{"text": "\n      \u201cYesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.\u201d\n  ", "author": "\n    Bill Keane\n  "}
{"text": "\n      \u201cI have not failed. I've just found 10,000 ways that won't work.\u201d\n  ", "author": "\n    Thomas A. Edison\n  "}
{"text": "\n      \u201cThe opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference.\u201d\n  ", "author": "\n    Elie Wiesel\n  "}
{"text": "\n      \u201cI am enough of an artist to draw freely upon my imagination. Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.\u201d\n  ", "author": "\n    Albert Einstein\n  "}
{"text": "\n      \u201cYou have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. You're on your own. And you know what you know. And YOU are the one who'll decide where to go...\u201d\n  ", "author": "\n    Dr. Seuss,\n  "}
{"text": "\n      \u201cIt is never too late to be what you might have been.\u201d\n  ", "author": "\n    George Eliot\n  "}
{"text": "\n      \u201cThis life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about.\u201d\n  ", "author": "\n    Marilyn Monroe\n  "}
{"text": "\n      \u201cThere is no greater agony than bearing an untold story inside you.\u201d\n  ", "author": "\n    Maya Angelou,\n  "}
{"text": "\n      \u201cEverything you can imagine is real.\u201d\n  ", "author": "\n    Pablo Picasso\n  "}
{"text": "\n      \u201cYou can never get a cup of tea large enough or a book long enough to suit me.\u201d\n  ", "author": "\n    C.S. Lewis\n  "}
{"text": "\n      \u201cLife isn't about finding yourself. Life is about creating yourself.\u201d\n  ", "author": "\n    George Bernard Shaw\n  "}
{"text": "\n      \u201cTo the well-organized mind, death is but the next great adventure.\u201d\n  ", "author": "\n    J.K. Rowling,\n  "}
{"text": "\n      \u201cDo what you can, with what you have, where you are.\u201d\n  ", "author": "\n    Theodore Roosevelt\n  "}
{"text": "\n      \u201cSuccess is not final, failure is not fatal: it is the courage to continue that counts.\u201d\n  ", "author": "\n    Winston S. Churchill\n  "}
{"text": "\n      \u201cListen to the mustn'ts, child. Listen to the don'ts. Listen to the shouldn'ts, the impossibles, the won'ts. Listen to the never haves, then listen close to me... Anything can happen, child. Anything can be.\u201d\n  ", "author": "\n    Shel Silverstein\n  "}
{"text": "\n      \u201cWhen one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.\u201d\n  ", "author": "\n    Helen Keller\n  "}
{"text": "\n      \u201cSo, this is my life. And I want you to know that I am both happy and sad and I'm still trying to figure out how that could be.\u201d\n  ", "author": "\n    Stephen Chbosky,\n  "}
{"text": "\n      \u201cAnd, when you want something, all the universe conspires in helping you to achieve it.\u201d\n  ", "author": "\n    Paulo Coelho,\n  "}
{"text": "\n      \u201cYou may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one.\u201d\n  ", "author": "\n    John Lennon\n  "}
{"text": "\n      \u201cOur deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. It is our light, not our darkness that most frightens us. We ask ourselves, 'Who am I to be brilliant, gorgeous, talented, fabulous?' Actually, who are you not to be? You are a child of God. Your playing small does not serve the world. There is nothing enlightened about shrinking so that other people won't feel insecure around you. We are all meant to shine, as children do. We were born to make manifest the glory of God that is within us. It's not just in some of us; it's in everyone. And as we let our own light shine, we unconsciously give other people permission to do the same. As we are liberated from our own fear, our presence automatically liberates others.\u201d\n  ", "author": "\n    Marianne Williamson,\n  "}
{"text": "\n      \u201cIt\u2019s no use going back to yesterday, because I was a different person then.\u201d\n  ", "author": "\n    Lewis Carroll\n  "}
{"text": "\n      \u201cIt's the possibility of having a dream come true that makes life interesting.\u201d\n  ", "author": "\n    Paulo Coelho,\n  "}
{"text": "\n      \u201cWhat you're supposed to do when you don't like a thing is change it. If you can't change it, change the way you think about it. Don't complain.\u201d\n  ", "author": "\n    Maya Angelou,\n  "}
{"text": "\n      \u201cHe\u2019s not perfect. You aren\u2019t either, and the two of you will never be perfect. But if he can make you laugh at least once, causes you to think twice, and if he admits to being human and making mistakes, hold onto him and give him the most you can. He isn\u2019t going to quote poetry, he\u2019s not thinking about you every moment, but he will give you a part of him that he knows you could break. Don\u2019t hurt him, don\u2019t change him, and don\u2019t expect for more than he can give. Don\u2019t analyze. Smile when he makes you happy, yell when he makes you mad, and miss him when he\u2019s not there. Love hard when there is love to be had. Because perfect guys don\u2019t exist, but there\u2019s always one guy that is perfect for you.\u201d\n  ", "author": "\n    Bob Marley\n  "}
{"text": "\n      \u201cI love to see a young girl go out and grab the world by the lapels. Life's a bitch. You've got to go out and kick ass.\u201d\n  ", "author": "\n    maya angelou\n  "}
{"text": "\n      \u201cIf you remember me, then I don't care if everyone else forgets.\u201d\n  ", "author": "\n    Haruki Murakami,\n  "}
{"text": "\n      \u201cTurn your wounds into wisdom.\u201d\n  ", "author": "\n    Oprah Winfrey\n  "}
{"text": "\n      \u201cTake responsibility of your own happiness, never put it in other people\u2019s hands.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cWhen you have eliminated all which is impossible, then whatever remains, however improbable, must be the truth.\u201d\n  ", "author": "\n    Arthur Conan Doyle,\n  "}
{"text": "\n      \u201cWar is peace. ", "author": "\n    George Orwell,\n  "}
{"text": "\n      \u201cBe the reason someone smiles. Be the reason someone feels loved and believes in the goodness in people.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cGreat things happen to those who don't stop believing, trying, learning, and being grateful.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cBe thankful for everything that happens in your life; it\u2019s all an experience.\u201d\n  ", "author": "\n    Roy T. Bennett\n  "}
{"text": "\n      \u201cTears are words that need to be written.\u201d\n  ", "author": "\n    Paulo Coelho\n  "}
{"text": "\n      \u201cSometimes you have to lose all you have to find out who you truly are.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cThere must be those among whom we can sit down and weep and still be counted as warriors.\u201d\n  ", "author": "\n    Adrienne Rich\n  "}
{"text": "\n      \u201cDon't let the bastards grind you down.\u201d\n  ", "author": "\n    Margaret Atwood,\n  "}
{"text": "\n      \u201cI don't think of all the misery, but of the beauty that still remains.\u201d\n  ", "author": "\n    Anne Frank,\n  "}
{"text": "\n      \u201cIt's not the size of the dog in the fight, it's the size of the fight in the dog.\u201d\n  ", "author": "\n    Mark Twain\n  "}
{"text": "\n      \u201cA person's a person, no matter how small.\u201d\n  ", "author": "\n    Dr. Seuss,\n  "}
{"text": "\n      \u201cWhen we honestly ask ourselves which person in our lives mean the most to us, we often find that it is those who, instead of giving advice, solutions, or cures, have chosen rather to share our pain and touch our wounds with a warm and tender hand. The friend who can be silent with us in a moment of despair or confusion, who can stay with us in an hour of grief and bereavement, who can tolerate not knowing, not curing, not healing and face with us the reality of our powerlessness, that is a friend who cares.\u201d\n  ", "author": "\n    Henri Nouwen,\n  "}
{"text": "\n      \u201cYou can't live your life for other people. You've got to do what's right for you, even if it hurts some people you love.\u201d\n  ", "author": "\n    Nicholas Sparks,\n  "}
{"text": "\n      \u201cWell-behaved women seldom make history.\u201d\n  ", "author": "\n    Laurel Thatcher Ulrich,\n  "}
{"text": "\n      \u201cWhen I despair, I remember that all through history the way of truth and love have always won. There have been tyrants and murderers, and for a time, they can seem invincible, but in the end, they always fall. Think of it--always.\u201d\n  ", "author": "\n    Mahatma Gandhi\n  "}
{"text": "\n      \u201cSo we beat on, boats against the current, borne back ceaselessly into the past.\u201d\n  ", "author": "\n    F. Scott Fitzgerald,\n  "}
{"text": "\n      \u201cNothing is impossible, the word itself says 'I'm possible'!\u201d\n  ", "author": "\n    Audrey Hepburn\n  "}
{"text": "\n      \u201cI can't give you a sure-fire formula for success, but I can give you a formula for failure: try to please everybody all the time.\u201d\n  ", "author": "\n    Herbert Bayard Swope\n  "}
{"text": "\n      \u201c[...]the only people for me are the mad ones, the ones who are mad to live, mad to talk, mad to be saved, desirous of everything at the same time, the ones who never yawn or say a commonplace thing, but burn, burn, burn like fabulous yellow roman candles exploding like spiders across the stars and in the middle you see the blue centerlight pop and everybody goes \u201cAwww!\u201d\n  ", "author": "\n    Jack Kerouac,\n  "}
{"text": "\n      \u201cDo what you feel in your heart to be right \u2013 for you\u2019ll be criticized anyway.\u201d\n  ", "author": "\n    Eleanor Roosevelt\n  "}
{"text": "\n      \u201cNever doubt that a small group of thoughtful, committed, citizens can change the world. Indeed, it is the only thing that ever has.\u201d\n  ", "author": "\n    Margaret Mead\n  "}
{"text": "\n      \u201cHappiness is not something ready made. It comes from your own actions.\u201d\n  ", "author": "\n    Dalai Lama XIV\n  "}
{"text": "\n      \u201cPeace begins with a smile..\u201d\n  ", "author": "\n    Mother Teresa\n  "}
{"text": "\n      \u201cDo not read, as children do, to amuse yourself, or like the ambitious, for the purpose of instruction. No, read in order to live.\u201d\n  ", "author": "\n    Gustave Flaubert\n  "}
{"text": "\n      \u201cImagining the future is a kind of nostalgia. (...) You spend your whole life stuck in the labyrinth, thinking about how you'll escape it one day, and how awesome it will be, and imagining that future keeps you going, but you never do it. You just use the future to escape the present.\u201d\n  ", "author": "\n    John Green,\n  "}
{"text": "\n      \u201cWhat lies behind us and what lies before us are tiny matters compared to what lies within us.\u201d\n  ", "author": "\n    Ralph Waldo Emerson\n  "}
{"text": "\n      \u201cFor attractive lips, speak words of kindness.", "author": "\n    Sam Levenson,\n  "}
{"text": "\n      \u201cFriendship is unnecessary, like philosophy, like art.... It has no survival value; rather it is one of those things which give value to survival.\u201d\n  ", "author": "\n    C.S. Lewis,\n  "}
{"text": "\n      \u201cPromise Yourself", "author": "\n    Christian D. Larson,\n  "}
{"text": "\n      \u201cI hope she'll be a fool -- that's the best thing a girl can be in this world, a beautiful little fool.\u201d\n  ", "author": "\n    F. Scott Fitzgerald,\n  "}
{"text": "\n      \u201cWhatever you are, be a good one.\u201d\n  ", "author": "\n    Abraham Lincoln\n  "}
{"text": "\n      \u201cMay you live every day of your life.\u201d\n  ", "author": "\n    Jonathan Swift\n  "}
{"text": "\n      \u201cTwo wrongs don't make a right, but they make a good excuse.\u201d\n  ", "author": "\n    Thomas Szasz\n  "}
{"text": "\n      \u201cWho controls the past controls the future. Who controls the present controls the past.\u201d\n  ", "author": "\n    George Orwell,\n  "}
{"text": "\n      \u201cFirst they ignore you. Then they ridicule you. And then they attack you and want to burn you. And then they build monuments to you.\u201d\n  ", "author": "\n    Nicholas Klein\n  "}
{"text": "\n      \u201cPrayer is not asking. It is a longing of the soul. It is daily admission of one's weakness. It is better in prayer to have a heart without words than words without a heart.\u201d\n  ", "author": "\n    Mahatma Gandhi\n  "}
{"text": "\n      \u201cBe mindful. Be grateful. Be positive. Be true. Be kind.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cIt isn't what you have or who you are or where you are or what you are doing that makes you happy or unhappy. It is what you think about it.\u201d\n  ", "author": "\n    Dale Carnegie,\n  "}
{"text": "\n      \u201cWhat I need is the dandelion in the spring. The bright yellow that means rebirth instead of destruction. The promise that life can go on, no matter how bad our losses. That it can be good again.\u201d\n  ", "author": "\n    Suzanne Collins,\n  "}
{"text": "\n      \u201cAccept yourself, love yourself, and keep moving forward. If you want to fly, you have to give up what weighs you down.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cLife is too short to waste your time on people who don\u2019t respect, appreciate, and value you.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cI don't trust people who don't love themselves and tell me, 'I love you.' ... There is an African saying which is: Be careful when a naked person offers you a shirt.\u201d\n  ", "author": "\n    Maya Angelou\n  "}
{"text": "\n      \u201cThe future belongs to those who believe in the beauty of their dreams.\u201d\n  ", "author": "\n    Eleanor Roosevelt\n  "}
{"text": "\n      \u201cAnd, in the end", "author": "\n    Paul McCartney,\n  "}
{"text": "\n      \u201cI like living. I have sometimes been wildly, despairingly, acutely miserable, racked with sorrow; but through it all I still know quite certainly that just to be alive is a grand thing.\u201d\n  ", "author": "\n    Agatha Christie\n  "}
{"text": "\n      \u201cI am not sure exactly what heaven will be like, but I know that when we die and it comes time for God to judge us, he will not ask, 'How many good things have you done in your life?' rather he will ask, 'How much love did you put into what you did?\u201d\n  ", "author": "\n    Mother Teresa\n  "}
{"text": "\n      \u201cI do not fear death. I had been dead for billions and billions of years before I was born, and had not suffered the slightest inconvenience from it.\u201d\n  ", "author": "\n    Mark Twain\n  "}
{"text": "\n      \u201cWe\u2019re all seeking that special person who is right for us. But if you\u2019ve been through enough relationships, you begin to suspect there\u2019s no right person, just different flavors of wrong. Why is this? Because you yourself are wrong in some way, and you seek out partners who are wrong in some complementary way. But it takes a lot of living to grow fully into your own wrongness. And it isn\u2019t until you finally run up against your deepest demons, your unsolvable problems\u2014the ones that make you truly who you are\u2014that we\u2019re ready to find a lifelong mate. Only then do you finally know what you\u2019re looking for. You\u2019re looking for the wrong person. But not just any wrong person: it's got to be the right wrong person\u2014someone you lovingly gaze upon and think, \u201cThis is the problem I want to have.\u201d", "author": "\n    Andrew  Boyd,\n  "}
{"text": "\n      \u201cIt\u2019s only after you\u2019ve stepped outside your comfort zone that you begin to change, grow, and transform.\u201d\n  ", "author": "\n    Roy T. Bennett\n  "}
{"text": "\n      \u201cLive the Life of Your Dreams: Be brave enough to live the life of your dreams according to your vision and purpose instead of the expectations and opinions of others.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cDon't judge each day by the harvest you reap but by the seeds that you plant.\u201d\n  ", "author": "\n    Robert Louis Stevenson\n  "}
{"text": "\n      \u201cBut I know, somehow, that only when it is dark enough can you see the stars.\u201d\n  ", "author": "\n    Martin Luther King, Jr.\n  "}
{"text": "\n      \u201cMore smiling, less worrying. More compassion, less judgment. More blessed, less stressed. More love, less hate.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cSimplicity, patience, compassion.", "author": "\n    Lao Tzu,\n  "}
{"text": "\n      \u201cThe past is a place of reference, not a place of residence; the past is a place of learning, not a place of living.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cNone but ourselves can free our minds.\u201d\n  ", "author": "\n    Bob Marley\n  "}
{"text": "\n      \u201cThe truth is, unless you let go, unless you forgive yourself, unless you forgive the situation, unless you realize that the situation is over, you cannot move forward.\u201d\n  ", "author": "\n    Steve Maraboli,\n  "}
{"text": "\n      \u201cSometimes our light goes out, but is blown again into instant flame by an encounter with another human being.\u201d\n  ", "author": "\n    Albert Schweitzer\n  "}
{"text": "\n      \u201cWhen one tugs at a single thing in nature, he finds it attached to the rest of the world.\u201d\n  ", "author": "\n    John Muir\n  "}
{"text": "\n      \u201cBelieve in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cDon\u2019t waste your time in anger, regrets, worries, and grudges. Life is too short to be unhappy.\u201d\n  ", "author": "\n    Roy T. Bennett\n  "}
{"text": "\n      \u201cDon't let the expectations and opinions of other people affect your decisions. It's your life, not theirs. Do what matters most to you; do what makes you feel alive and happy. Don't let the expectations and ideas of others limit who you are. If you let others tell you who you are, you are living their reality \u2014 not yours. There is more to life than pleasing people. There is much more to life than following others' prescribed path. There is so much more to life than what you experience right now. You need to decide who you are for yourself. Become a whole being. Adventure.\u201d\n  ", "author": "\n    Roy T. Bennett\n  "}
{"text": "\n      \u201cDo what is right, not what is easy nor what is popular.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cClouds come floating into my life, no longer to carry rain or usher storm, but to add color to my sunset sky.\u201d\n  ", "author": "\n    Rabindranath Tagore,\n  "}
{"text": "\n      \u201cIf you want to be happy, do not dwell in the past, do not worry about the future, focus on living fully in the present.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cPeople say nothing is impossible, but I do nothing every day.\u201d\n  ", "author": "\n    A.A. Milne,\n  "}
{"text": "\n      \u201cThe brick walls are there for a reason. The brick walls are not there to keep us out. The brick walls are there to give us a chance to show how badly we want something. Because the brick walls are there to stop the people who don\u2019t want it badly enough. They\u2019re there to stop the other people.\u201d\n  ", "author": "\n    Randy Pausch,\n  "}
{"text": "\n      \u201cA woman's heart should be so hidden in God that a man has to seek Him just to find her.\u201d\n  ", "author": "\n    Maya Angelou\n  "}
{"text": "\n      \u201cAnyone can hide. Facing up to things, working through them, that's what makes you strong.\u201d\n  ", "author": "\n    Sarah Dessen\n  "}
{"text": "\n      \u201cplease believe that things are good with me, and even when they're not, they will be soon enough. And i will always believe the same about you.\u201d\n  ", "author": "\n    Stephen Chbosky,\n  "}
{"text": "\n      \u201cI will love you always. When this red hair is white, I will still love you. When the smooth softness of youth is replaced by the delicate softness of age, I will still want to touch your skin. When your face is full of the lines of every smile you have ever smiled, of every surprise I have seen flash through your eyes, when every tear you have ever cried has left its mark upon your face,I will treasure you all the more, because I was there to see it all. I will share your life with you, Meredith, and I will love you until the last breath leaves your body or mine.\u201d\n  ", "author": "\n    Laurell K. Hamilton,\n  "}
{"text": "\n      \u201cYou are not rich until you have a rich heart.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cStop comparing yourself to other people, just choose to be happy and live your own life.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cNever be bullied into silence. Never allow yourself to be made a victim. Accept no one's definition of your life, but define yourself.\u201d\n  ", "author": "\n    Harvey Fierstein\n  "}
{"text": "\n      \u201cYou never change your life until you step out of your comfort zone; change begins at the end of your comfort zone.\u201d\n  ", "author": "\n    Roy T. Bennett\n  "}
{"text": "\n      \u201cI kept always two books in my pocket, one to read, one to write in.\u201d\n  ", "author": "\n    Robert Louis Stevenson,\n  "}
{"text": "\n      \u201cIn the end", "author": "\n    Jack Kornfield,\n  "}
{"text": "\n      \u201cDo not let the memories of your past limit the potential of your future. There are no limits to what you can achieve on your journey through life, except in your mind.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cI must be a mermaid, Rango. I have no fear of depths and a great fear of shallow living.\u201d\n  ", "author": "\n    Anais Nin\n  "}
{"text": "\n      \u201cLife is too short to waste any amount of time on wondering what other people think about you. In the first place, if they had better things going on in their lives, they wouldn't have the time to sit around and talk about you. What's important to me is not others' opinions of me, but what's important to me is my opinion of myself.\u201d\n  ", "author": "\n    C. JoyBell C.\n  "}
{"text": "\n      \u201cGreat heroes need great sorrows and burdens, or half their greatness goes unnoticed. It is all part of the fairy tale.\u201d\n  ", "author": "\n    Peter S. Beagle,\n  "}
{"text": "\n      \u201cI'd rather be hated for who I am, than loved for who I am not.\u201d\n  ", "author": "\n    Kurt Cobain\n  "}
{"text": "\n      \u201cAtticus, he was real nice.\"", "author": "\n    Harper Lee,\n  "}
{"text": "\n      \u201cSo many people walk around with a meaningless life. They seem half-asleep, even when they're busy doing things they think are important. This is because they're chasing the wrong things. The way you get meaning into your life is to devote yourself to loving others, devote yourself to your community around you, and devote yourself to creating something that gives you purpose and meaning.\u201d\n  ", "author": "\n    Mitch Albom,\n  "}
{"text": "\n      \u201cParents can only give good advice or put them on the right paths, but the final forming of a person's character lies in their own hands.\u201d\n  ", "author": "\n    Anne Frank\n  "}
{"text": "\n      \u201cI wonder how many people don't get the one they want, but end up with the one they're supposed to be with.\u201d\n  ", "author": "\n    Fannie Flagg,\n  "}
{"text": "\n      \u201cTrees that are slow to grow bear the best fruit.\u201d\n  ", "author": "\n    Moliere\n  "}
{"text": "\n      \u201cDon't Just", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cThe things you do for yourself are gone when you are gone, but the things you do for others remain as your legacy.\u201d\n  ", "author": "\n    Kalu Ndukwe Kalu\n  "}
{"text": "\n      \u201cEven if you cannot change all the people around you, you can change the people you choose to be around. Life is too short to waste your time on people who don\u2019t respect, appreciate, and value you. Spend your life with people who make you smile, laugh, and feel loved.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cDare to Be", "author": "\n    Steve Maraboli,\n  "}
{"text": "\n      \u201cYou cannot control the behavior of others, but you can always choose how you respond to it.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cLife becomes easier and more beautiful when we can see the good in other people.\u201d\n  ", "author": "\n    Roy T. Bennett\n  "}
{"text": "\n      \u201cA painter should begin every canvas with a wash of black, because all things in nature are dark except where exposed by the light.\u201d\n  ", "author": "\n    Leonardo da Vinci\n  "}
{"text": "\n      \u201cA woman's heart should be so hidden in God that a man has to seek Him just to find her.\u201d\n  ", "author": "\n    Max Lucado\n  "}
{"text": "\n      \u201cIt's kind of fun to do the impossible.\u201d\n  ", "author": "\n    Walt Disney\n  "}
{"text": "\n      \u201cPain is temporary. Quitting lasts forever.\u201d\n  ", "author": "\n    Lance Armstrong Sally Jenkins,\n  "}
{"text": "\n      \u201cThe most important kind of freedom is to be what you really are. You trade in your reality for a role. You trade in your sense for an act. You give up your ability to feel, and in exchange, put on a mask. There can't be any large-scale revolution until there's a personal revolution, on an individual level. It's got to happen inside first.\u201d\n  ", "author": "\n    Jim MORRISON\n  "}
{"text": "\n      \u201cDon't be afraid of your fears. They're not there to scare you. They're there to let you know that something is worth it.\u201d\n  ", "author": "\n    C. JoyBell C.\n  "}
{"text": "\n      \u201cWhen I was a little girl I used to read fairy tales. In fairy tales you meet Prince Charming and he's everything you ever wanted. In fairy tales the bad guy is very easy to spot. The bad guy is always wearing a black cape so you always know who he is. Then you grow up and you realize that Prince Charming is not as easy to find as you thought. You realize the bad guy is not wearing a black cape and he's not easy to spot; he's really funny, and he makes you laugh, and he has perfect hair.\u201d\n  ", "author": "\n    Taylor Swift\n  "}
{"text": "\n      \u201cI was smiling yesterday,I am smiling today and I will smile tomorrow.Simply because life is too short to cry for anything.\u201d\n  ", "author": "\n    Santosh Kalwar,\n  "}
{"text": "\n      \u201cYou never fail until you stop trying.\u201d\n  ", "author": "\n    Albert Einstein\n  "}
{"text": "\n      \u201cAll the darkness in the world cannot extinguish the light of a single candle.\u201d\n  ", "author": "\n    St. Francis Of Assisi,\n  "}
{"text": "\n      \u201cIf you want to forget something or someone, never hate it, or never hate him/her. Everything and everyone that you hate is engraved upon your heart; if you want to let go of something, if you want to forget, you cannot hate.\u201d\n  ", "author": "\n    C. JoyBell C.\n  "}
{"text": "\n      \u201cHope", "author": "\n    Alfred Lord Tennyson\n  "}
{"text": "\n      \u201cStart writing, no matter what. The water does not flow until the faucet is turned on.\u201d\n  ", "author": "\n    Louis L'Amour\n  "}
{"text": "\n      \u201cThe Chinese use two brush strokes to write the word 'crisis.' One brush stroke stands for danger; the other for opportunity. In a crisis, be aware of the danger--but recognize the opportunity.\u201d\n  ", "author": "\n    John F. Kennedy\n  "}
{"text": "\n      \u201cStories never really end...even if the books like to pretend they do. Stories always go on. They don't end on the last page, any more than they begin on the first page.\u201d\n  ", "author": "\n    Cornelia Funke,\n  "}
{"text": "\n      \u201cWhy didn't I learn to treat everything like it was the last time. My greatest regret was how much I believed in the future.\u201d\n  ", "author": "\n    Jonathan Safran Foer,\n  "}
{"text": "\n      \u201cTo see a World in a Grain of Sand ", "author": "\n    William Blake,\n  "}
{"text": "\n      \u201cNever lose hope. Storms make people stronger and never last forever.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cThe worst part of success is trying to find someone who is happy for you.\u201d\n  ", "author": "\n    Bette Midler\n  "}
{"text": "\n      \u201cShe seems so cool, so focused, so quiet, yet her eyes remain fixed upon the horizon. You think you know all there is to know about her immediately upon meeting her, but everything you think you know is wrong. Passion flows through her like a river of blood. ", "author": "\n    Neil Gaiman,\n  "}
{"text": "\n      \u201cThere are some things you can't share without ending up liking each other, and knocking out a twelve-foot mountain troll is one of them.\u201d\n  ", "author": "\n    J. K. Rowling,\n  "}
{"text": "\n      \u201cNo matter what he does, every person on earth plays a central role in the history of the world. And normally he doesn't know it.\u201d\n  ", "author": "\n    Paulo Coelho,\n  "}
{"text": "\n      \u201cYou should never be surprised when someone treats you with respect, you should expect it.\u201d\n  ", "author": "\n    Sarah Dessen,\n  "}
{"text": "\n      \u201cThere was another life that I might have had, but I am having this one.\u201d\n  ", "author": "\n    Kazuo Ishiguro\n  "}
{"text": "\n      \u201cIt does not matter how slowly you go as long as you do not stop.\u201d\n  ", "author": "\n    Confucius\n  "}
{"text": "\n      \u201cWhat's the good of living if you don't try a few things?\u201d\n  ", "author": "\n    Charles M. Schulz\n  "}
{"text": "\n      \u201cNothing in the world is ever completely wrong. Even a stopped clock is right twice a day.\u201d\n  ", "author": "\n    Paulo Coelho,\n  "}
{"text": "\n      \u201cThe purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.\u201d\n  ", "author": "\n    Eleanor Roosevelt\n  "}
{"text": "\n      \u201cChange will not come if we wait for some other person, or if we wait for some other time. We are the ones we've been waiting for. We are the change that we seek.\u201d\n  ", "author": "\n    Barack Obama\n  "}
{"text": "\n      \u201cLack of direction, not lack of time, is the problem. We all have twenty-four hour days.\u201d\n  ", "author": "\n    Zig Ziglar\n  "}
{"text": "\n      \u201cIf people refuse to look at you in a new light and they can only see you for what you were, only see you for the mistakes you've made, if they don't realize that you are not your mistakes, then they have to go.\u201d\n  ", "author": "\n    Steve Maraboli,\n  "}
{"text": "\n      \u201cKindness is a language which the deaf can hear and the blind can see.\u201d\n  ", "author": "\n    Mark Twain\n  "}
{"text": "\n      \u201cGo on with what your heart tells you, or you will lose all.\u201d\n  ", "author": "\n    Rick Riordan,\n  "}
{"text": "\n      \u201cIf you think you are too small to make a difference, try sleeping with a mosquito.\u201d\n  ", "author": "\n    Dalai Lama XIV\n  "}
{"text": "\n      \u201cTry a little harder to be a little better.\u201d\n  ", "author": "\n    Gordon B. Hinckley\n  "}
{"text": "\n      \u201cReputation is what other people know about you. Honor is what you know about yourself.\u201d\n  ", "author": "\n    Lois McMaster Bujold,\n  "}
{"text": "\n      \u201cThe important thing to you is not how many years in your life, but how much life in your years!\u201d\n  ", "author": "\n    Edward J. Stieglitz\n  "}
{"text": "\n      \u201cTime doesn\u2019t heal emotional pain, you need to learn how to let go.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cEvery book, every volume you see here, has a soul. The soul of the person who wrote it and of those who read it and lived and dreamed with it. Every time a book changes hands, every time someone runs his eyes down its pages, its spirit grows and strengthens.\u201d\n  ", "author": "\n    Carlos Ruiz Zaf\u00f3n,\n  "}
{"text": "\n      \u201cEven strength must bow to wisdom sometimes.\u201d\n  ", "author": "\n    Rick Riordan,\n  "}
{"text": "\n      \u201cAll parents damage their children. It cannot be helped. Youth, like pristine glass, absorbs the prints of its handlers. Some parents smudge, others crack, a few shatter childhoods completely into jagged little pieces, beyond repair.\u201d\n  ", "author": "\n    Mitch Albom,\n  "}
{"text": "\n      \u201cI meant what I said and I said what I meant. An elephant's faithful one-hundred percent!\u201d\n  ", "author": "\n    Dr. Seuss,\n  "}
{"text": "\n      \u201cRemember, darkness does not always equate to evil, just as light does not always bring good.\u201d\n  ", "author": "\n    P.C. Cast,\n  "}
{"text": "\n      \u201cTo shine your brightest light is to be who you truly are.\u201d\n  ", "author": "\n    Roy T. Bennett\n  "}
{"text": "\n      \u201cMy concern is not whether God is on our side; my greatest concern is to be on God's side, for God is always right.\u201d\n  ", "author": "\n    Abraham Lincoln\n  "}
{"text": "\n      \u201cWhen I was about eight, I decided that the most wonderful thing, next to a human being, was a book.\u201d\n  ", "author": "\n    Margaret Walker\n  "}
{"text": "\n      \u201cWhat do we live for, if it is not to make life less difficult for each other?\u201d\n  ", "author": "\n    George Eliot\n  "}
{"text": "\n      \u201cMake improvements, not excuses. Seek respect, not attention.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cKeep Going", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cPursue what catches your heart, not what catches your eyes.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cYou're off to Great Places!", "author": "\n    Dr. Seuss,\n  "}
{"text": "\n      \u201cSuccess is not how high you have climbed, but how you make a positive difference to the world.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cWell, now", "author": "\n    Pablo Neruda,\n  "}
{"text": "\n      \u201cWe have to allow ourselves to be loved by the people who really love us, the people who really matter. Too much of the time, we are blinded by our own pursuits of people to love us, people that don't even matter, while all that time we waste and the people who do love us have to stand on the sidewalk and watch us beg in the streets! It's time to put an end to this. It's time for us to let ourselves be loved.\u201d\n  ", "author": "\n    C. JoyBell C.\n  "}
{"text": "\n      \u201cIt is the time you have wasted for your rose that makes your rose so important.\u201d\n  ", "author": "\n    Antoine de Saint-Exup\u00e9ry,\n  "}
{"text": "\n      \u201cLearn to light a candle in the darkest moments of someone\u2019s life. Be the light that helps others see; it is what gives life its deepest significance.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cDon't say you don't have enough time. You have exactly the same number of hours per day that were given to Helen Keller, Pasteur, Michelangelo, Mother Teresa, Leonardo da Vinci, Thomas Jefferson, and Albert Einstein.\u201d\n  ", "author": "\n    H. Jackson Brown Jr.\n  "}
{"text": "\n      \u201cOnce you have tasted flight, you will forever walk the earth with your eyes turned skyward, for there you have been, and there you will always long to return.\u201d\n  ", "author": "\n    Leonardo da Vinci\n  "}
{"text": "\n      \u201cThe thing about growing up with Fred and George,\" said Ginny thoughtfully, \"is that you sort of start thinking anything's possible if you've got enough nerve.\u201d\n  ", "author": "\n    J. K. Rowling,\n  "}
{"text": "\n      \u201cBe grateful for what you already have while you pursue your goals. ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cThe secret of health for both mind and body is not to mourn for the past, nor to worry about the future, but to live the present moment wisely and earnestly.\u201d\n  ", "author": "\n    Bukkyo Dendo Kyokai,\n  "}
{"text": "\n      \u201cOne love, one heart, one destiny.\u201d\n  ", "author": "\n    Robert Marley\n  "}
{"text": "\n      \u201cBelieve in Your Heart", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cIf she's amazing, she won't be easy. If she's easy, she won't be amazing. If she's worth it, you wont give up. If you give up, you're not worthy. ... Truth is, everybody is going to hurt you; you just gotta find the ones worth suffering for.\u201d\n  ", "author": "\n    Bob Marley,\n  "}
{"text": "\n      \u201cDance, when you're broken open. Dance, if you've torn the bandage off. Dance in the middle of the fighting. Dance in your blood. Dance when you're perfectly free.\u201d\n  ", "author": "\n    Rumi\n  "}
{"text": "\n      \u201cNo amount of regretting can change the past, and no amount of worrying can change the future.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cTreat everyone with politeness and kindness, not because they are nice, but because you are.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cSo be sure when you step, Step with care and great tact. And remember that life's A Great Balancing Act. And will you succeed? Yes! You will, indeed! (98 and \u00be percent guaranteed) Kid, you'll move mountains.\u201d\n  ", "author": "\n    Dr. Seuss,\n  "}
{"text": "\n      \u201cAny fool can be happy. It takes a man with real heart to make beauty out of the stuff that makes us weep.\u201d\n  ", "author": "\n    Clive Barker,\n  "}
{"text": "\n      \u201cStart each day with a positive thought and a grateful heart.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cActs of Kindness:", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cIt's not the face, but the expressions on it. It's not the voice, but what you say. It's not how you look in that body, but the thing you do with it. You are beautiful.\u201d\n  ", "author": "\n    Stephenie Meyer,\n  "}
{"text": "\n      \u201cYou is kind. You is smart. You is important.\u201d\n  ", "author": "\n    Kathryn Stockett,\n  "}
{"text": "\n      \u201cFollow your heart, listen to your inner voice, stop caring about what others think.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cTop 15 Things Money Can\u2019t Buy", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cUnderstanding is the first step to acceptance, and only with acceptance can there be recovery.\u201d\n  ", "author": "\n    J.K. Rowling,\n  "}
{"text": "\n      \u201cIs 'fat' really the worst thing a human being can be? Is 'fat' worse than 'vindictive', 'jealous', 'shallow', 'vain', 'boring' or 'cruel'? Not to me.\u201d\n  ", "author": "\n    J.K. Rowling\n  "}
{"text": "\n      \u201cI believe that imagination is stronger than knowledge. That myth is more potent than history. That dreams are more powerful than facts. That hope always triumphs over experience. That laughter is the only cure for grief. And I believe that love is stronger than death.\u201d\n  ", "author": "\n    Robert Fulghum,\n  "}
{"text": "\n      \u201cIf my life is going to mean anything, I have to live it myself.\u201d\n  ", "author": "\n    Rick Riordan,\n  "}
{"text": "\n      \u201cAnd once the storm is over, you won\u2019t remember how you made it through, how you managed to survive. You won\u2019t even be sure, whether the storm is really over. But one thing is certain. When you come out of the storm, you won\u2019t be the same person who walked in. That\u2019s what this storm\u2019s all about.\u201d\n  ", "author": "\n    Haruki Murakami,\n  "}
{"text": "\n      \u201cYou can't stay in your corner of the Forest waiting for others to come to you. You have to go to them sometimes.\u201d\n  ", "author": "\n    A.A. Milne,\n  "}
{"text": "\n      \u201cIsn't it nice to think that tomorrow is a new day with no mistakes in it yet?\u201d\n  ", "author": "\n    L.M. Montgomery\n  "}
{"text": "\n      \u201cAttitude is a choice. Happiness is a choice. Optimism is a choice. Kindness is a choice. Giving is a choice. Respect is a choice. Whatever choice you make makes you. Choose wisely.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cHope is the thing with feathers ", "author": "\n    Emily Dickinson\n  "}
{"text": "\n      \u201cYou can talk with someone for years, everyday, and still, it won't mean as much as what you can have when you sit in front of someone, not saying a word, yet you feel that person with your heart, you feel like you have known the person for forever.... connections are made with the heart, not the tongue.\u201d\n  ", "author": "\n    C. JoyBell C.\n  "}
{"text": "\n      \u201cPain is inevitable. Suffering is optional.\u201d\n  ", "author": "\n    haruki murakami,\n  "}
{"text": "\n      \u201cWhen I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down \u2018happy\u2019. They told me I didn\u2019t understand the assignment, and I told them they didn\u2019t understand life.\u201d\n  ", "author": "\n    John Lennon\n  "}
{"text": "\n      \u201cIf you're reading this...", "author": "\n    Chad Sugg,\n  "}
{"text": "\n      \u201cAlways do what you are afraid to do.\u201d\n  ", "author": "\n    Ralph Waldo Emerson\n  "}
{"text": "\n      \u201cThere is neither happiness nor misery in the world; there is only the comparison of one state with another, nothing more. He who has felt the deepest grief is best able to experience supreme happiness. We must have felt what it is to die, Morrel, that we may appreciate the enjoyments of life. ", "author": "\n    Alexandre Dumas\n  "}
{"text": "\n      \u201cOur lives begin to end the day we become silent about things that matter.\u201d\n  ", "author": "\n    Martin Luther King Jr.,\n  "}
{"text": "\n      \u201cThe mind is its own place, and in itself can make a heaven of hell, a hell of heaven..\u201d\n  ", "author": "\n    John Milton,\n  "}
{"text": "\n      \u201cTalent hits a target no one else can hit. Genius hits a target no one else can see.\u201d\n  ", "author": "\n    Arthur Schopenhauer\n  "}
{"text": "\n      \u201cIn the end, we will remember not the words of our enemies, but the silence of our friends.\u201d\n  ", "author": "\n    Martin Luther King Jr.\n  "}
{"text": "\n      \u201cDo not let your fire go out, spark by irreplaceable spark in the hopeless swamps of the not-quite, the not-yet, and the not-at-all. Do not let the hero in your soul perish in lonely frustration for the life you deserved and have never been able to reach. The world you desire can be won. It exists.. it is real.. it is possible.. it's yours.\u201d\n  ", "author": "\n    Ayn Rand,\n  "}
{"text": "\n      \u201cIt is so hard to leave\u2014until you leave. And then it is the easiest goddamned thing in the world.\u201d\n  ", "author": "\n    John Green,\n  "}
{"text": "\n      \u201cDon't be pushed around by the fears in your mind. Be led by the dreams in your heart.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cFantasy is hardly an escape from reality. It's a way of understanding it.\u201d\n  ", "author": "\n    Lloyd Alexander\n  "}
{"text": "\n      \u201cThe world is indeed full of peril, and in it there are many dark places; but still there is much that is fair, and though in all lands love is now mingled with grief, it grows perhaps the greater.\u201d\n  ", "author": "\n    J.R.R. Tolkien,\n  "}
{"text": "\n      \u201cWaiting is painful. Forgetting is painful. But not knowing which to do is the worst kind of suffering.\u201d\n  ", "author": "\n    Paulo Coelho,\n  "}
{"text": "\n      \u201cIt is not the critic who counts; not the man who points out how the strong man stumbles, or where the doer of deeds could have done them better. The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood; who strives valiantly; who errs, who comes short again and again, because there is no effort without error and shortcoming; but who does actually strive to do the deeds; who knows great enthusiasms, the great devotions; who spends himself in a worthy cause; who at the best knows in the end the triumph of high achievement, and who at the worst, if he fails, at least fails while daring greatly, so that his place shall never be with those cold and timid souls who neither know victory nor defeat.\u201d\n  ", "author": "\n    Theodore Roosevelt\n  "}
{"text": "\n      \u201cDo not go where the path may lead, go instead where there is no path and leave a trail.\u201d\n  ", "author": "\n    Ralph Waldo Emerson\n  "}
{"text": "\n      \u201cHell is empty and all the devils are here.\u201d\n  ", "author": "\n    William Shakespeare,\n  "}
{"text": "\n      \u201cInstead of worrying about what you cannot control, shift your energy to what you can create.\u201d\n  ", "author": "\n    Roy T. Bennett,\n  "}
{"text": "\n      \u201cNever let your sense of morals prevent you from doing what is right.\u201d\n  ", "author": "\n    Isaac Asimov,\n  "}
{"text": "\n      \u201cI can be changed by what happens to me. But I refuse to be reduced by it.", "author": "\n    Maya Angelou,\n  "}
{"text": "\n      \u201cIf you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.\u201d\n  ", "author": "\n    Martin Luther King Jr.\n  "}
